apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: he96o52ys-go 
  janus-idp.io/tekton: he96o52ys-go
  backstage.io/kubernetes-id: he96o52ys-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: he96o52ys-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml