apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: he96o52ys-go-gitops
  description: This is GitOps manifest for he96o52ys-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=he96o52ys-go
    backstage.io/kubernetes-id: he96o52ys-go 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhtap-rhdh-qe/he96o52ys-go-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:he96o52ys-go
