apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: he96o52ys-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: he96o52ys-go 
  name: he96o52ys-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: he96o52ys-go 
